Map<String, String> imagePath = {
  ..._svgImagePath,
  ..._pngImagePath,
  ..._jpegImagePath,
  ..._svgCategoryIconImagePath
};

Map<String, String> _svgImagePath = {
  "discover_icon": "assets/svg/discover_icon.svg",
  "home_vector": "assets/svg/home_vector.svg",
  "home_hollow_icon": "assets/svg/home_hollow_icon.svg",
  "explore_hollow_icon": "assets/svg/explore_hollow_icon.svg",
  "location_icon": "assets/svg/location_icon.svg",
  "arrow_icon": "assets/svg/arrow_icon.svg",
  "search_icon": "assets/svg/search_icon.svg",
  "calendar_icon": "assets/svg/calendar_icon.svg",
  "map_link_icon": "assets/svg/map_link_icon.svg",
  "location_card_icon": "assets/svg/location_card_icon.svg",
  "man_icon": "assets/svg/man_icon.svg",
  "paw_icon": "assets/svg/paw_icon.svg",
  "transport_icon": "assets/svg/transport_icon.svg",
  "eye_open": "assets/svg/eye_open.svg",
  "eye_closed": "assets/svg/eye_closed.svg",
  "map_fav": "assets/svg/map_fav.svg",
  "mail_icon": "assets/svg/mail_icon.svg",
  "phone_icon": "assets/svg/phone_icon.svg",
  "online_services": "assets/svg/online_services_icon.svg",
  "place_holder_icon": "assets/svg/place_holder_icon.svg",
  "news_icon": "assets/svg/news_icon.svg",
  "bus_icon": "assets/svg/bus_icon.svg",
  "glass_icon": "assets/svg/glass_icon.svg",
  "cap_icon": "assets/svg/cap_icon.svg",
  "groups": "assets/svg/groups.svg",
  "taxi_icon": "assets/svg/taxi_icon.svg",
  "train_icon": "assets/svg/train_icon.svg",
  "alert_icon": "assets/svg/alert_icon.svg",
  "chat_icon": "assets/svg/chat_icon.svg",
  "man_icon_2": "assets/svg/man_icon_2.svg",
  "expand_full": "assets/svg/expand_full.svg",
  "tourism_service_image": "assets/svg/tourism_service_image.svg",
  "virtual_town_hall_map_image": "assets/svg/virtual_town_hall_map_image.svg",
  "heart_icon": "assets/svg/heart_icon.svg",
  "home_icon": "assets/svg/home_icon.svg",
  "brain_teaser_icon": "assets/svg/brain_teaser_icon.svg",
  "trophy_icon" : "assets/svg/trophy_icon.svg",
  "digifit_trophy_icon": "assets/svg/digifit_trophy_icon.svg",
  "dumble_icon": "assets/svg/dumble_icon.svg",
  "snow_icon": "assets/svg/snow_icon.svg",
  "sunny_icon": "assets/svg/sunny_icon.svg",
  "rainy_icon": "assets/svg/rainy_icon.svg",
  "partly_cloudy_icon": "assets/svg/partly_cloudy_icon.svg",
  "correct":"assets/svg/correct.svg",
  "filter_button":"assets/svg/filter_button.svg",
  "lock":"assets/svg/lock.svg",
  "circular_check_outline":"assets/svg/circular_check_outlined.svg",
  "circular_check_filled":"assets/svg/circular_check_filled.svg",
  "setting_header_image":"assets/svg/setting_header_image.svg",
  "setting_profile":"assets/svg/setting_profile.svg",
  "my_fav":"assets/svg/my_fav.svg",
  "forward_arrow":"assets/svg/forward_arrow.svg",
  "location_icon_selected":"assets/svg/location_icon_selected.svg"
};

Map<String, String> _pngImagePath = {
  "dino": "assets/png/dino.png",
  "feedback_image.png": "assets/png/feedback_image.png",
  "home_screen_background": "assets/png/home_screen_background.png",
  "background_image": "assets/png/home_screen_background.png",
  "calendar": "assets/png/calendar.png",
  "map_icon": "assets/png/map_icon.png",
  "news_icon": "assets/png/news_icon.png",
  "dino_with_bg": "assets/png/dino_with_bg.png",
  "explore": "assets/png/explore.png",
  "star": "assets/png/star.png",
  "onboarding_background": "assets/png/onboarding_background.png",
  "onboarding_logo": "assets/png/onboarding_logo.png",
  "sunny_image": "assets/png/sunny_image.png",
  "cold_image": "assets/png/cold_image.png",
  "rain_image": "assets/png/rain_image.png",
  "spring_image": "assets/png/spring_image.png",
  "empty_profile_image": "assets/png/empty_profile_image.png",
  "filter_icon": "assets/png/filter_icon.png",
  "virtual_town_hall": "assets/png/virtual_townhall.png",
  "my_town": "assets/png/my_town.png",
  "tourism_and_lesiure": "assets/png/tourism_and_lesiure.png",
  "mobility": "assets/png/mobility.png",
  "get_involved": "assets/png/get_involved.png",
  "digifit": "assets/png/digifit.png",
  "city_background_image": "assets/png/city_background_image.png",
  "mail": "assets/png/mail.png",
  "phone": "assets/png/phone.png",
  "crest": "assets/png/crest.png",
  "map_image": "assets/png/map_image.png",
  "kusel_map_image": "assets/png/kusel_map_image.png",
  "participate_image": "assets/png/participate_image.png",
  "link_icon": "assets/png/link_icon.png",
  "scan_icon": "assets/png/scan_icon.png",
  "digifit_map_image": "assets/png/digifit_map_image.png",
  "exercise_background": "assets/png/exercise_background.png",
  "sun_weather_image": "assets/png/sun_weather.png",
  "boldi_game_details_image": "assets/png/boldi_game_details.png",
  "stamps_icon": "assets/png/stamps_icon.png",
  "cloud_message_image": "assets/png/cloud_message.png",
  "grid_boldi": "assets/png/grid_boldi.png",
  "boldi_successor": "assets/png/boldi_successor.png",
  "unlock_stamp_image": "assets/png/unlock_stamp_image.png",
  "cloud_image_math_hunt": "assets/png/cloud_image_math_hunt.png",
  "boldi_new_sunny_image": "assets/png/boldi_new_sunny.png",
  "math_hunt_boldi": "assets/png/math_hunt_boldi.png",
  "digit_dash_boldi_image": "assets/png/boldi_digit_dash.png",
  "digit_dash_cloud_image": "assets/png/cloud_digit_dash_image.png",
  "placeholder_image_pictures_game": "assets/png/place_holder_image_pictures_game.png",
  "scanner_image": "assets/png/scanner_image.png",
  "arrow_right": "assets/png/arrow_right.png",
  "setting_boldi": "assets/png/setting_boldi.png",
};

Map<String, String> _jpegImagePath = {
  "highlight_card_image": "assets/jpg/highlight_card_image.jpg",
  "digifit_overview_image": "assets/jpg/digifit_overview_image.jpg",
};

Map<String, String> _svgCategoryIconImagePath = {
  "sideseeing_and_attraction_category_icon":
      "assets/svg/category_icon/sideseeing_and_attraction.svg",
  "gastro_category_icon": "assets/svg/category_icon/gastro.svg",
  "event_category_icon": "assets/svg/category_icon/event.svg",
  "parks_and_nature_category_icon":
      "assets/svg/category_icon/park_and_nature.svg",
  "shopping_category_icon": "assets/svg/category_icon/shopping.svg",
  "accommodation_category_icon": "assets/svg/category_icon/accommodation.svg",
  "sports": "assets/svg/category_icon/sports.svg",
  "facilities_category_icon": "assets/svg/category_icon/facilities.svg",
  "fav_category_icon": "assets/svg/category_icon/fav.svg",
  "placeholder_category_icon":"assets/svg/category_icon/placeholder.svg",
  "tourism_service_map_image": "assets/svg/category_icon/tourism_service_map_image.svg",
  "highlights_map": "assets/svg/category_icon/highlights_map.svg"
};
